name: Build Gluon
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build_firmware:
    strategy:
      fail-fast: false
      matrix:
        target: [ x86-64, ramips-mt76x8, ramips-mt7620, ath79-generic ]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Dependencies
        run: sudo ci/install-dependencies.sh
      - name: Update gluon-site supmodule
        run: ci/update-site.sh
      - name: Build
        run: ci/run-build.sh ${{ matrix.target }}
      - name: Archive build output
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.target }}_output
          path: gluon/output

