name: Build Gluon
on:
  push:
    branches:
      - main
    paths:
      - "modules"
      - "Makefile"
      - "scripts/**"
      - "package/**"
      - "patches/**"
      - "targets/**"
      - ".github/workflows/build-gluon.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "modules"
      - "Makefile"
      - "scripts/**"
      - "package/**"
      - "patches/**"
      - "targets/**"
      - ".github/workflows/build-gluon.yml"
jobs:
  build_firmware:
    strategy:
      fail-fast: false
      matrix:
        target: [ x86-64, ramips-mt76x8 ]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: sudo ci/install-dependencies.sh
      - name: Build
        run: ci/run-build.sh ${{ matrix.target }}
      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.target }}_logs
          path: openwrt/logs
      - name: Archive build output
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.target }}_output
          path: output

