name: Build Gluon
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build_firmware:
    strategy:
      fail-fast: false
      matrix:
        target: [ x86-64, ramips-mt76x8 ]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install git subversion python3 build-essential gawk unzip libncurses-dev libz-dev libssl-dev wget time qemu-utils
          git clone https://github.com/freifunk-gluon/gluon.git gluon -b v2021.1
          cd gluon
          git clone https://github.com/AS207111/gluon-site.git site
          make update
          make GLUON_TARGET=${{ matrix.target }}
      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.target }}_logs
          path: gluon/openwrt/logs
      - name: Archive build output
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.target }}_output
          path: gluon/output

